title: Dialectique
# icon: i-circle-flags-fr
navigation:
  order: 3
  meta:
    language:
      code: en
      label: English
      shortLabel: EN
    edition: translation
    editionLabel: Translations
