title: Dialectique
# icon: i-circle-flags-fr
navigation:
  order: 2
  meta:
    language:
      code: pt
      label: Português
      shortLabel: PT
    edition: translation
    editionLabel: Tradução
